[tools]
go = "1.25.4"
golangci-lint = "2.5.0"
kustomize = "5.7.1"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "0.19.0"
"go:github.com/google/go-licenses" = "1.6.0"
kind = "0.31.0"
kubectl = "1.32.1"
helm = "3.16.4"
helmfile = "1.2.3"
kubebuilder = "4.10.1"
"github:kyverno/chainsaw" = "0.2.14"
yq = "4.45.1"
jq = "1.7.1"
