apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelcache-status-updater
rules:
- apiGroups: ["aim.eai.amd.com"]
  resources: ["aimmodelcaches/status"]
  verbs: ["get", "patch", "update"]