# This rule is not used by the project aim-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over aim.eai.amd.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aim-engine
    app.kubernetes.io/managed-by: kustomize
  name: aimmodel-admin-role
rules:
- apiGroups:
  - aim.eai.amd.com
  resources:
  - aimmodels
  verbs:
  - '*'
- apiGroups:
  - aim.eai.amd.com
  resources:
  - aimmodels/status
  verbs:
  - get
