apiVersion: aim.eai.amd.com/v1alpha1
kind: AIMModelCache
metadata:
  labels:
    app.kubernetes.io/name: aim-engine
    app.kubernetes.io/managed-by: kustomize
  name: aimmodelcache-sample
spec:
  # TODO(user): Add fields here
