# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/aim.eai.amd.com_aimclustermodels.yaml
- bases/aim.eai.amd.com_aimclustermodelsources.yaml
- bases/aim.eai.amd.com_aimclusterruntimeconfigs.yaml
- bases/aim.eai.amd.com_aimclusterservicetemplates.yaml
- bases/aim.eai.amd.com_aimmodelcaches.yaml
- bases/aim.eai.amd.com_aimmodels.yaml
- bases/aim.eai.amd.com_aimruntimeconfigs.yaml
- bases/aim.eai.amd.com_aimservices.yaml
- bases/aim.eai.amd.com_aimservicetemplates.yaml
- bases/aim.eai.amd.com_aimtemplatecaches.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
